### ISSUE TITLE
Typ in der Antwort

### ISSUE THREAD

**Issue by Jaykju** [aletutto/fae-antwort-webinterface#1]
Ich hatte für den Inhalt einer Nachricht wie zum Beispiel [hier](https://github.com/aletutto/fae-antwort-webinterface/blob/8bb9d1d2ef728bb6180910c8b98964e53a8ea4f9/index.js#L8) eigentlich mehr so etwas im Kopf wie `positiv` und `negativ` oder `angenommen` und `abgelehnt` bzw. einfach `ja` und `nein`, aber ich denke das müssen wir nochmal im Team besprechen.

**Comment by aletutto** [comment]
Das sollte definitiv so sein, im Besten Falle erstellen wir in unserem Service dann noch ein entsprechendes ENUM dafür.
